### ISSUE TITLE
Check location of Orinoco and Murrumbidgee?

### ISSUE THREAD

**Issue by kadrlica** [cmateu/galstreams#1]
Thank you for the very nice tool and compilation of stream coordinates!

Would it be possible to double check the locations of Murrumbidgee and Orinoco? If these are coordinates taken from [Grillmair 2017](https://arxiv.org/abs/1708.09029) then I don't think they should extend as far south (in celestial coordinates) as is shown in the example figure. 

Apologies in advance if my very precursory glance is wrong.

**Comment by cmateu** [comment]
Hi Alex, thanks for your comments. 

I’ve checked this and can’t find any errors so far, but I think I see where the doubt comes from. 

For Murrumbidge, I’ve assumed Grillmair 2017’s equation 3 for the ra(dec) relationship, with dec in the range [-65,+16], so as to include the fiducial point quoted by G17 in his Table 1. Although this is larger than the range [-65,-30] mentioned in the paper, this is not referred to explicitly as the range of validity of that equation and, if  assumed, the length of the stream would be shorter than the reported 95º. More importantly, assuming the range only up to dec=-30 the reported 
fiducial point would be left out of the stream by over 40º. 

For Orinoco I don’t see any mistakes either. I’ve assumed eq. (4) for dec(ra) and restricted it
to the range -62.<b<-48, which G17 says includes a faint feature of the stream seen by Koposov+ (2014) and still results in a plausible orbit.

So I guess these might be kind of `generous’ limits for both streams in some sense.

I’ll  ask C. Grillmair directly about this just to make triple-sure though.

Thanks and best regards. C.

**Comment by kadrlica** [comment]
Thanks for the quick response. This explains how the streams are being extended outside of the Pan-STARRS footprint. I guess it is a philosophical question about whether the extents in the `galstream` tables are meant to span the regions where the streams are directly (and confidently) measured, or whether they should be extended to connect putative features that may be associated with the streams.

I guess even more philosophical is where to draw the threshold for inclusion in these lists. Have you considered sub-categories of objects based on their confidence level?

**Comment by kadrlica** [comment]
@cmateu I just checked the [Orinoco file](https://github.com/cmateu/galstreams/blob/master/footprints/individual_footprints/galstreams.footprint.Orinoco.dat) more closely and it only has *DEC* values extending from -48 to -64. Pan-STARRS does not go below RA < -30 and the figures from Koposov et al. 2014 don't go below DEC < -40. Is it possible that you have a Galactic to Celestial coordinate conversion error?

**Comment by cmateu** [comment]
Yes, I completely agree with you. I’ve been thinking about how to implement a further classification into confirmer/high-confidence/tentative
or so, but this might have to extend not just to each stream but even to parts of a stream I would say. 

For the time being I’ve tried to be as inclusive as possible because the main purpose was to provide a guide to
the locations of known streams and some other substructure/overdensities to compare new discoveries against.

But the goal is to extend this progressively to include more detailed information, and this classification would certainly be part of that.

I think this is something I could implement in the short term, e.g. a broad classification to quickly plot only high-confidence and preliminary candidates. 
If you have any thoughts or suggestions they’re most welcome.

**Comment by cmateu** [comment]
So, I think I’ve found the source of confusion. The coordinates are generated based on Eq. 4  from G17b,
which G17b says applies to the eastern 19º of Orinoco. These coordinate range is not quoted explicitly in ra/dec
 and I understood from the text that it corresponds to the part with -62º<b<-48º, but I now see I missunderstood,
it seems this corresponds to a ‘faint feature’ that might be an extension of the stream. The coordinates are quite
difficult to read off the figure, so I’ve contacted C. Grillmair to check the proper coordinate limits for the stream.
Will get back to you onces this is figured out.

**Comment by kadrlica** [comment]
From the red lines on Fig 1 of Grillmair, I estimate that Orinoco runs from l,b ~ (230, -80) to l,b ~ (20, -47). This corresponds to a valid RA range for Eq. 4 from -36 < RA < 23.

I'll also note that it looks like the shape of the Murrumbidgee stream is not quite right when it approaches ATLAS, Kwando, and Orinoco. In Fig 1 of Grillmair the lines associated with these streams nearly intersect, while the `galstreams` file version of Murrumidgee passes noticeably far from the end of Kwando. I've tried re-generating the path from Eq. 3 of Grillmair, and this appears an inconsistency between Eq. 3 and Fig. 1 in his paper.

**Comment by cmateu** [comment]
Thanks for the notes Alex. I've already contacted Carl Grillmair about this to confirm the Orinoco coordinates. Thanks also for confirming the apparent inconsistency between his Eq. 3 and Fig. 1. I'll get back to you on this, Carl is also checking the southern extension of the Orphan stream as there is a bit of wiggle in the place where it connects with the northern part, but this is a much smaller thing compared to the other (apparent) inconsistencies.

**Comment by cmateu** [comment]
I’ve updated the footprints for Orinoco and Murrumbidgee like this:

- For Orinoco (Ori), G17b says Eq. 5 is only valid for the eastern 19deg but does not state
explicit an exact range of validity for the equation. Following your suggestion, I limited
it to RA>324 or RA<23. This seems to produce a footprint consistent with G17b’s Fig. 1b.
The putative western extension of Ori is not included in the footprint

- For Murrumbidgee (Mur), there is no range of validity reported in G17b for Eq. 3. This was limited to l<150deg to comply with his Fig. 1. This does not fix the fact you point out that Kwando and Mur do not intersect as they seem to in Fig. 1. This seems to be because the footprint generated for Kwando is limited to 19<ra<31, the range over which G17b claims it is detect at 7sigma, but the lines in Fig.1 extend further. There is no way to tell from the text, however, if Kwando extends further at lower significance.

My bet that the lines in Fig. 1 might extend more than the streams do, just being there for illustrative purposes. So I kept the reported range but will try to get confirmation from C. Grillmair.

With these caveats, Kwando and Molonglo were checked again and seem to be consistent with G17b-Fig.1, more points were added to densify their footprints.
