### ISSUE TITLE
Pal 5  total velocity > 1000km/s in Galactocentric coordintes.

### ISSUE THREAD

**Issue by appy2806** [cmateu/galstreams#26]
When I use astropy to convert Pal 5 velocites in galactocentric coordaintes using the following code:

```
import astropy.coordinates as ac
import galstreams
mwsts = galstreams.MWStreams(verbose=False, implement_Off=False)
gsr = ac.Galactocentric()
st_name = 'Pal5-S20'
coords_st = mwsts[st_name].track.transform_to(gsr)
```

The total velocities for stream particles > 1000 km/s which seems rather high? Even for the highly eccentric orbit it's on?

**Comment by cmateu** [comment]
Actually these values are meaningless since the Pal5-S20 track does not have any proper motion information, it only has sky coordinates+distance. You can check whether a given track has proper motion info by checking InfoFlag[2], 0=False, 1=True, 2=True_but_caveat(see paper). You can also check the same info in the has_pm column of the summary table (mwsts.summary['has_pm'], same convention). For Pal5 kinematic data better use the PW19 (recommended, see paper) or I21 tracks.

**Comment by appy2806** [comment]
Thanks for the prompt response
!
